name: CI/CD Pipeline

on:
  push:
    # branches:
    #   - master
jobs:
  unit_tests:
    name: Running some unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test -- --coverage

  build:
    runs-on: ubuntu-latest
    needs: unit_tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build
