name: CI/CD Pipeline

on:
  push:
    # branches:
    #   - master
jobs:
  unit_tests:
    name: Checking Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test -- --coverage

  build:
    runs-on: ubuntu-latest
    needs: unit_tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./build

  deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./build

      - name: Check the files
        run: ls ./build

      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: "128.24.74.209"
          username: "asifazure"
          password: ${{ secrets.PASSWORD }}
          source: "./build"
          target: docu-build
